# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-16 11:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('problem', models.TextField()),
                ('figure_name', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=100)),
                ('attempt', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('school_id', models.CharField(max_length=100)),
                ('subject', models.CharField(default=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='response',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Student'),
        ),
    ]
