# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-16 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='subject',
            field=models.CharField(default='EE147', max_length=100),
        ),
    ]
