# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-17 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_auto_20161116_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='figure_name',
            new_name='figure',
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.CharField(default='EE147', max_length=100),
        ),
    ]
