# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-09 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_response_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='is_last',
            field=models.BooleanField(default=False),
        ),
    ]
